const priceM2 = 10; //dolares
const arrayDiameter = ["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "2 1/2", "3", "4", "5", "6"," 8", "10", "12", "14", "16", "18", "20", "24"];
const arrayAccesory = ["elbow90", "elbow45", "tee", "reduction", "flange", "lengthTube"];

let jsonDiameter = [ {"diam": "1/2"}, 
                     {"diam": "3/4"},
                     {"diam": "1"},
                     {"diam": "1 1/4"},
                     {"diam": "1 1/2"},
                     {"diam": "2"},
                     {"diam": "2 1/2"},
                     {"diam": "3"},
                     {"diam": "4"},
                     {"diam": "5"},
                     {"diam": "6"},
                     {"diam": "8"},
                     {"diam": "10"},
                     {"diam": "12"},
                     {"diam": "14"},
                     {"diam": "16"},
                     {"diam": "18"},
                     {"diam": "20"},
                     {"diam": "24"},
]

let jsonElbow90 = [ {"diam": "1/2", "factor": 0.030},
                    {"diam": "3/4", "factor": 0.045},
                    {"diam": "1", "factor": 0.060},
                    {"diam": "1 1/4", "factor": 0.075},
                    {"diam": "1 1/2", "factor": 0.090},
                    {"diam": "2", "factor": 0.120},
                    {"diam": "2 1/2", "factor": 0.150},
                    {"diam": "3", "factor": 0.180},
                    {"diam": "4", "factor": 0.240},
                    {"diam": "5", "factor": 0.300},
                    {"diam": "6", "factor": 0.360},
                    {"diam": "8", "factor": 0.480},
                    {"diam": "10", "factor": 0.600},
                    {"diam": "12", "factor": 0.720},
                    {"diam": "14", "factor": 0.840},
                    {"diam": "16", "factor": 0.960},
                    {"diam": "18", "factor": 1.080},
                    {"diam": "20", "factor": 1.200},
                    {"diam": "24", "factor": 1.450},
];
